# -*- coding: utf-8 -*-
"""Lecture 0. jupyter_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lJeMY-QB0binFuksP2VGHrufyclkwoD

# Вступ
Мене **звати** Іван!   

Я пишу код на *Python*!

Ця програма робить щось корисне.
"""

print('Hello world!')

120+20

"""## Розділ 1
просто текст

### Підрозділ

## Розділ 2
"""

import time

for i in range(10):
    print(i)
    time.sleep(30)

my_list = [1, 2, 3, 4]

my_list

"""В мене є список
* Один
    - підсписок
        - це
  - інший підписок
        - то
        - і ще то
* два
  - підсписок
"""

[x**2 for x in range(-10, 11)]

s = 'Hello world!'

print(s)

1+1
print(2+22)
3+3
s

a = 'Hello everyone!'

a

import matplotlib.pyplot as plt
import numpy as np

plt.plot(np.sin(range(20)));

"""## Розділ 3"""

a = 1
b = 2
a + b

a/b

